### ISSUE TITLE
Is it down?

### ISSUE THREAD

**Issue by benoittgt** [HirbodBehnam/RedditDownloaderBot#15]
Hello

Thanks for the bot. It seems it is doesn't react anymore on Telegram.

**Comment by edmxn** [comment]
The same thing happens to me, I hope it works again.

**Comment by laosiji888** [comment]
I create a similar one on telegram

https://t.me/RedditDownloader2023Bot

**Comment by edmxn** [comment]
> I create a similar one on telegram
> 
> https://t.me/RedditDownloader2023Bot

It's not working now, is it temporary?
