### ISSUE TITLE
Handle Telegram Character Limit for Long Reddit Post Captions

### ISSUE THREAD

**Issue by AliAryanTech** [HirbodBehnam/RedditDownloaderBot#31]
Currently, when the caption or text of a Reddit post exceeds Telegram's 4,096-character limit, the bot fails to send the message.  

### Suggested Solutions:  
1. Split the text into parts and send it sequentially.  
2. Send the text as a `document.txt` file instead.  

If the bot were written in Python or JS/TS, I'd be happy to contribute. Since it's in Go, I hope you can address this issue.  

Thank you!

**Comment by HirbodBehnam** [comment]
Hi
I think sending it as a separate file is a good idea! I'll try to implement it.
